"""jobOpening education column added

Revision ID: 38366fd970bd
Revises: 1a5e5670cd98
Create Date: 2024-09-15 13:51:57.182622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38366fd970bd'
down_revision = '1a5e5670cd98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_opening', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_opening', schema=None) as batch_op:
        batch_op.drop_column('education')

    # ### end Alembic commands ###
