"""Describe the changes here

Revision ID: 534207431a9b
Revises: 
Create Date: 2024-08-10 16:53:07.934462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534207431a9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('experienceLevel', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('jobType', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('jobType')
        batch_op.drop_column('experienceLevel')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
